import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';import {runInNewContext} from 'node:vm';
import {renderView,previewView,COUNT_FIELDS,geometryLevel} from '../src/render-view.js';import {mapEdgeLight,MapLightCache} from '../src/map-light.js';import {edgeLight} from '../src/photo-light.js';
function fixture(){const r={geometry:{points:[[50,14],[50,14.001],[50,14.002]],edges:[[0,1],[1,2]],ids:[4,5],display:[[[50,14],[50,14.002],[5,6],[]]]},journeys:7,routeCounts:{0:{0:7},1:{0:7}},edgeRoutes:{0:[0],1:[0]},edgeAgencies:{0:[0],1:[0]}};for(const f of COUNT_FIELDS)r[f]=new Uint32Array([f==='counts'?7:f==='surfaceForward'||f==='forward'?7:0,f==='counts'?7:f==='surfaceForward'||f==='forward'?7:0]);return r;}
test('Build LODs preserve source IDs, topology, shape anchors, identities and pixel error',()=>{const p=spawnSync('python',['-c',`
from scripts.render_geometry import display_levels,retained
p=[[50,14],[50.00001,14.001],[50,14.002],[50.001,14.001]]
g={'edges':[[0,p[0],p[1]],[1,p[1],p[2]],[2,p[1],p[3]]]};a=[[(0,0,1,1)]]*3
for level,rows in display_levels(g,a).items():
 assert sorted(abs(ref)-1 for row in rows for ref in row[2])==[0,1,2]
 assert all(len(row[2])==1 for row in rows)
g['edges']=g['edges'][:2]
assert len(display_levels(g,a)['overview'])==1
assert len(display_levels(g,a,{tuple(p[1])})['overview'])==2
assert retained(p[:3],4)==[0,2]
assert retained(p[:3],0)==[0,1,2]
a[1]=[(1,0,1,1)]
assert len(display_levels(g,a)['overview'])==2
`],{encoding:'utf8'});assert.equal(p.status,0,p.stderr);assert.equal(geometryLevel(11),'overview');assert.equal(geometryLevel(14),'medium');assert.equal(geometryLevel(15),'detail');});
test('Display never sums adjacent counts and falls back at dynamic frequency/identity boundaries',()=>{const r=fixture(),d=renderView(r,10);assert.equal(d.geometry.edges.length,1);assert.equal(d.counts[0],7);assert.equal(d.geometry.samples.length,6);assert.deepEqual(d.memberIds,[[4,5]]);r.counts[1]=8;assert.equal(renderView(r,10).geometry.edges.length,2);r.counts[1]=7;r.edgeRoutes[1]=[1];assert.equal(renderView(r,10).geometry.edges.length,2);});
test('Display reverses directional counts and preserves exact source bearings',()=>{const r=fixture();r.geometry.display=[[[50,14.002],[50,14],[-6,-5],[]]];const d=renderView(r,10);assert.equal(d.forward[0],0);assert.equal(d.backward[0],7);assert.equal(d.surfaceBackward[0],7);assert.equal(d.geometry.edges.length,1);assert.deepEqual(d.memberIds,[[5,4]]);assert.ok(d.geometry.samples[2]>260);});
test('Preview filters correlated route/agency identities and never claims sun or frequency',()=>{const chunks=[{segments:[[[50,14],[50,14.002],[5],[[0,0,1,1],[1,1,-1,1]]]]}],meta={routes:[['a','a','',3,0,0],['b','b','',1,0,0]]},f={routes:[0],agencies:[1],modes:[],operation:'all'};assert.equal(previewView(chunks,meta,f,10,[49,13,51,15]).counts.length,0);const p=previewView(chunks,meta,{...f,agencies:[]},10,[49,13,51,15]);assert.equal(p.preliminary,true);assert.equal(p.journeys,null);let calls=0;assert.equal(mapEdgeLight(p.geometry,p,0,0,()=>calls++,()=>calls++).combined,'#88999b');assert.equal(calls,0);});
test('Exact light is preserved; simplified bend uses worst actual constituent, metro bypasses',()=>{const r=fixture(),g=renderView(r,10).geometry,sun={altitude:20,azimuth:270};let calls=0;const get=()=>{calls++;return sun;};r.surfaceForward.fill(0);mapEdgeLight(g,r,0,0,get,()=>null);assert.equal(calls,0);r.surfaceForward.fill(7);const exact=edgeLight(7,0,()=>sun,()=>null,g.samples[2]);assert.equal(mapEdgeLight(g,r,0,0,get,()=>null).combined,exact.combined);g.samples[5]=(g.samples[2]+180)%360;const lights=[g.samples[2],g.samples[5]].map(b=>edgeLight(7,0,()=>sun,()=>null,b));assert.equal(mapEdgeLight(g,r,0,0,get,()=>null).combined,lights[0].combined);});
test('Sun cache is restricted to one instant and can release a previous viewport',()=>{const c=new MapLightCache();assert.equal(c.sun(new Date(0),50,14),c.sun(new Date(0),50,14));c.sun(new Date(1),50,15);assert.equal(c.suns.size,1);c.clear();assert.equal(c.suns.size,0);});
test('Intensity UI defaults off, has a touch target and toggles only rendering',()=>{const html=readFileSync('public/index.html','utf8'),css=readFileSync('public/style.css','utf8'),app=readFileSync('src/app.js','utf8');assert.match(html,/id="intensity-toggle" type="checkbox">/);assert.match(css,/intensity-control[^}]*min-height:44px/);const handler=app.match(/\$\('intensity-toggle'\)\.onchange=.*?;\};/)[0];const el={checked:true},calls=[];const c={$:()=>el,intensities:false,routesLayer:{draw:()=>calls.push('draw')},drawLegend:()=>calls.push('legend')};runInNewContext(handler,c);el.onchange();assert.equal(c.intensities,true);assert.deepEqual(calls,['draw','legend']);});
test('Large photo draw yields across frames and cancels previous paints without changing geometry',()=>{
 const app=readFileSync('src/app.js','utf8'),method=app.slice(app.indexOf('  draw(){'),app.indexOf('  *paint(){'));const queued=[],cancelled=[],c={photoMode:true,requestAnimationFrame:fn=>(queued.push(fn),queued.length),cancelAnimationFrame:id=>cancelled.push(id)};runInNewContext('globalThis.layer={'+method+'};',c);let visits=0;c.layer.paint=function*(){visits++;yield;visits++;yield;visits++;};c.layer.visibleEdges=new Array(20001);c.layer.draw();assert.equal(visits,1);c.layer.draw();assert.deepEqual(cancelled,[1]);queued[0]();assert.equal(visits,2);queued[1]();assert.equal(visits,3);c.layer.visibleEdges=[];c.layer.draw();assert.equal(visits,6);
});
