import test from 'node:test';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
import {BuildingLoader,buildingAt,decodeBuildings} from '../src/buildings.js';import {directSun,environmentLight,horizonHeight} from '../src/environment.js';
const profile=(lower=10,upper=20,flag=0)=>({exact:new Uint16Array(72).fill(lower*10),estimated:new Uint16Array(72),upper:new Uint16Array(72).fill(upper*10),flags:new Uint8Array(72).fill(flag)}),sun=(altitude=5,azimuth=180)=>({altitude,azimuth});
test('building blocks below lower horizon, clears above upper, uncertain between bounds',()=>{assert.equal(buildingAt(sun(),profile()).state,'blocked');assert.equal(buildingAt(sun(25),profile()).state,'clear');assert.equal(buildingAt(sun(15),profile()).state,'unknown');});
test('building outside solar azimuth does not block, sectors preserve a narrow blocker',()=>{const p=profile(0,0);p.exact[36]=100;p.upper[36]=200;assert.equal(buildingAt(sun(5,180),p).state,'blocked');assert.equal(buildingAt(sun(5,190),p).state,'clear');assert.equal(buildingAt(sun(15,182.5),p).state,'unknown');});
test('north wrap and no linear interpolation of building sector envelopes',()=>{const p=profile(0,0);p.exact[71]=100;p.upper[71]=100;assert.equal(buildingAt(sun(5,355),p).state,'blocked');assert.equal(buildingAt(sun(5,-.01),p).state,'blocked');assert.equal(buildingAt(sun(5,360),p).state,'clear');const t=Array(72).fill(0);t[71]=100;assert.equal(horizonHeight(t,357.5),5);});
test('exact and estimated height retain provenance, unknown height never confirms sun',()=>{const p=profile(0,20,2);p.estimated.fill(100);assert.equal(buildingAt(sun(),p).quality,'estimated');assert.equal(buildingAt(sun(),p).state,'blocked');assert.equal(buildingAt(sun(25),p).quality,'estimated');p.flags.fill(1);assert.equal(buildingAt(sun(85),p).state,'unknown');assert.equal(buildingAt(sun(),null).state,'unknown');});
test('DEM and buildings retain both blockers; missing sources cannot give good light',()=>{const t=Array(72).fill(100),b=buildingAt(sun(),profile());assert.deepEqual(directSun(sun(),t,b).reasons,['terrain','building']);assert.deepEqual(directSun(sun(15),Array(72).fill(200),buildingAt(sun(15),profile(0,0))).reasons,['terrain']);assert.deepEqual(directSun(sun(),Array(72).fill(0),b).reasons,['building']);for(const [terrain,building] of [[null,b],[t,{state:'unknown'}],[null,{state:'unknown'}]])assert.notEqual(directSun(sun(),terrain,building).state,'clear');assert.equal(directSun(sun(25),null,buildingAt(sun(25),profile())).state,'unknown');assert.equal(directSun(sun(),Array(72).fill(0),{state:'unknown'}).state,'unknown');assert.equal(directSun(sun(),null,{state:'unknown'}).state,'unknown');assert.equal(directSun(sun(-1),null,{state:'unknown'}).state,'night');const l=environmentLight({level:'good',score:1},directSun(sun(25),null,buildingAt(sun(25),profile())));assert.equal(l.level,'unknown');assert.equal(l.score,0);});
function fixture(){const b=new ArrayBuffer(8+512),v=new DataView(b);new Uint8Array(b,0,4).set(new TextEncoder().encode('SFB1'));v.setUint32(4,1,true);v.setInt32(8,500000,true);v.setInt32(12,100000,true);return b;}
test('binary decoder validates corrupted chunks and keeps typed views',()=>{const b=fixture(),d=decodeBuildings(b);assert.equal(d.rows.size,1);assert.equal(d.rows.get('500000,100000').exact.buffer,b);assert.throws(()=>decodeBuildings(b.slice(0,-1)));new DataView(b).setUint16(16,901,true);assert.throws(()=>decodeBuildings(b));});
const index={version:1,step:5,cell:[.0001,.00015],model:{tile:.01},chunks:{'5000:1500':{bounds:[50,15,50.01,15.01],status:'profiles',path:'a',bytes:100},'5000:1501':{bounds:[50,15.01,50.01,15.02],status:'profiles',path:'b',bytes:100}}};
test('normal map does not fetch; detail lazy loads and slider uses cache without fetch',async()=>{let manifests=0,requests=0;const l=new BuildingLoader({manifest:async()=>{manifests++;return index;},load:async()=>{requests++;return {rows:new Map([['500000,100000',profile()]])};}});await l.update([50,15,50,15]);assert.equal(manifests+requests,0);await l.update([50,15,50,15],{enabled:true});assert.equal(requests,1);for(let i=0;i<500;i++)buildingAt(sun(i/10),l.at(50,15));assert.equal(requests,1);await l.update([50,15,50,15],{enabled:true});assert.equal(requests,1);});
test('chunk boundary chooses deterministic geographic cell; eviction and retry work',async()=>{let n=0;const l=new BuildingLoader({manifest:async()=>index,maxEntries:1,load:async()=>{n++;return {rows:new Map()};}});await l.update([50,15,50,15],{enabled:true});await l.update([50,15.015,50,15.015],{enabled:true});await l.update([50,15,50,15],{enabled:true});assert.equal(n,3);let failed=true;const r=new BuildingLoader({manifest:async()=>index,load:async()=>{if(failed)throw Error('network');return {rows:new Map()};}});await r.update([50,15,50,15],{enabled:true});assert.equal(r.error,true);assert.equal(r.at(50,15),null);failed=false;await r.update([50,15,50,15],{enabled:true});assert.equal(r.error,false);});
test('empty source coverage differs from absent chunk and invalid manifest retries',async()=>{let fail=true;const l=new BuildingLoader({manifest:async()=>{if(fail)throw Error('manifest');return {...index,chunks:{'5000:1500':{bounds:[50,15,50.01,15.01],status:'empty'}}};}});await l.update([50,15,50,15],{enabled:true});assert.equal(l.at(50,15),null);fail=false;await l.update([50,15,50,15],{enabled:true});assert.equal(buildingAt(sun(),l.at(50,15)).state,'clear');assert.equal(l.at(49,14),null);});
test('stale viewport response cannot replace current or disabled state',async()=>{let resolve;const l=new BuildingLoader({manifest:async()=>index,load:()=>new Promise(r=>resolve=r)});const old=l.update([50,15,50,15],{enabled:true});await new Promise(r=>setImmediate(r));await l.update([50,15,50,15]);resolve({rows:new Map()});await old;assert.equal(l.active.size,0);});
test('Python footprint, height model, geographical cache and source halo tests',()=>{const r=spawnSync('python',['tests/buildings_test.py'],{encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);});

test('detail layer stays lazy until a point is selected and is separate from map cache',async()=>{let requests=0;const root={...index,detail:{...index,cell:[.0001,.00015]}};const l=new BuildingLoader({layer:'detail',manifest:async()=>root,load:async()=>{requests++;return {rows:new Map()};}});await l.update([50,15,50,15]);assert.equal(requests,0);await l.update([50,15,50,15],{point:[50,15]});assert.ok(requests>0);});

test('local bridge or covered geometry overrides flat-ground building bounds',()=>{const p=profile(30,90,4),b=buildingAt(sun(15),p);assert.equal(b.state,'unknown');assert.equal(b.reason,'structure');assert.equal(directSun(sun(15),Array(72).fill(0),b).state,'unknown');p.flags.fill(1);assert.equal(buildingAt(sun(15),p).state,'blocked');});

test('overlapping viewport reuses active buffers larger than the LRU without fetching again',async()=>{let n=0;const l=new BuildingLoader({manifest:async()=>index,maxBytes:100,maxEntries:1,maxActiveBytes:200,load:async()=>{n++;return {rows:new Map()};}});await l.update([50,15,50.01,15.02],{enabled:true});assert.equal(n,2);await l.update([50,15,50.01,15.02],{enabled:true,point:[50,15]});assert.equal(n,2);});
