import test from 'node:test';
import assert from 'node:assert/strict';
import {horizonHeight,terrainLight,weatherAt} from '../src/environment.js';
test('horizon wraps north and interpolates angles',()=>{const p=Array(72).fill(0);p[71]=100;p[0]=200;assert.equal(horizonHeight(p,357.5),15);assert.equal(horizonHeight(p,360),20);assert.equal(horizonHeight(p,-2.5),15);});
test('terrain blocks only sun below local skyline',()=>{const p=Array(72).fill(80);assert.equal(terrainLight({altitude:5,azimuth:120},p),true);assert.equal(terrainLight({altitude:9,azimuth:120},p),false);assert.equal(terrainLight({altitude:-1,azimuth:120},p),false);assert.ok(!terrainLight({altitude:5,azimuth:120},null));});
test('weather uses timestamps and does not reuse forecast outside its range',()=>{const d={hourly:{time:[1000,4600],visibility:[500,null],cloud_cover:[90,30],direct_normal_irradiance_instant:[0,300]}};assert.equal(weatherAt(d,new Date(1100*1000)).visibility,500);assert.equal(weatherAt(d,new Date(5000*1000)).visibility,null);assert.equal(weatherAt(d,new Date(8200*1000)),null);assert.equal(weatherAt(null,new Date()),null);});

import {weatherGrid,weatherTint,interpolateTint} from '../src/environment.js';
test('grid covers viewport, stays bounded and gets finer when zooming in',()=>{const wide=weatherGrid({south:49.3,north:50.9,west:13,east:16}),close=weatherGrid({south:50.34,north:50.37,west:14.45,east:14.49});assert.ok(wide.sites.length<=64);assert.ok(close.spacing<wide.spacing);assert.ok(close.south<=50.34&&close.west<=14.45);assert.ok(close.south+(close.rows-1)*close.dy>=50.37);assert.ok(close.west+(close.cols-1)*close.dx>=14.49);});
test('fog is stronger than cloud haze; clear conditions stay transparent',()=>{const clear=weatherTint({visibility:20000,cloud:0,direct:700}),fog=weatherTint({visibility:400,cloud:95,direct:0}),cloud=weatherTint({visibility:20000,cloud:100,direct:0});assert.equal(clear.alpha,0);assert.ok(fog.alpha>cloud.alpha);assert.ok(fog.b>fog.r);assert.equal(weatherTint(null),null);assert.equal(weatherTint({visibility:null,cloud:null}),null);assert.equal(weatherTint({visibility:20000,cloud:100,direct:0},false).alpha,0);});
test('interpolation preserves missing areas and premultiplies transparency',()=>{const dark={r:80,g:100,b:150,alpha:.6},clear={r:145,g:150,b:158,alpha:0};const t=interpolateTint([dark,clear,dark,clear],2,2,.5,.5);assert.ok(Math.abs(t.alpha-.3)<1e-9);assert.equal(t.r,80);assert.equal(interpolateTint([dark,null,dark,clear],2,2,.5,.5),null);assert.equal(interpolateTint([dark,dark,dark,dark],2,2,-1,.5),null);});
